server:
  port: :4000
  version: 1.0
  jwtSecret: 38324

redis:
  address: 127.0.0.1:6379
  password:

etcd:
  address: 127.0.0.1:2379

domain:
  user: user
  video: video
  interact: main
  relation: main
  message: message
  cos: main